---
- name: install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present

- name: configure /etc/dnf/automatic.conf
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    mode: 0644
    owner: root
    group: root

- name: enable dnf-automatic service
  service:
    name: dnf-automatic.timer
    state: started
    enabled: true
